export const LOAD_ALL_CUSTOMERS = 'LOAD_ALL_CUSTOMERS';
export const LOAD_ALL_CUSTOMERS_SUCCESS = 'LOAD_ALL_CUSTOMERS_SUCCESS';
export const LOAD_ALL_CUSTOMERS_FAIL = 'LOAD_ALL_CUSTOMERS_FAIL';
export const ACTIVE_CUSTOMER = 'ACTIVE_CUSTOMER';
export const RESET_ACTIVE_CUSTOMER = 'RESET_ACTIVE_CUSTOMER';
export const TOGGLE_CUSTOMER_ADD_FORM = 'TOGGLE_CUSTOMER_ADD_FORM';
export const POST_CUSTOMER_ADD_FORM = 'POST_CUSTOMER_ADD_FORM';
export const POST_CUSTOMER_ADD_FORM_SUCCESS = 'POST_CUSTOMER_ADD_FORM_SUCCESS';
export const POST_CUSTOMER_ADD_FORM_FAIL = 'POST_CUSTOMER_ADD_FORM_FAIL';
export const TOGGLE_CUSTOMER_CHANGE_FORM = 'TOGGLE_CUSTOMER_CHANGE_FORM';
export const PUT_CUSTOMER_CHANGE_FORM = 'PUT_CUSTOMER_CHANGE_FORM';
export const PUT_CUSTOMER_CHANGE_FORM_SUCCESS = 'PUT_CUSTOMER_CHANGE_FORM_SUCCESS';
export const PUT_CUSTOMER_CHANGE_FORM_FAIL = 'PUT_CUSTOMER_CHANGE_FORM_FAIL';
export const TOGGLE_CUSTOMER_DELETE_FORM = 'TOGGLE_CUSTOMER_DELETE_FORM';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_FAIL = 'DELETE_CUSTOMER_FAIL';

export const URL = {
    CUSTOMERS: 'http://localhost:8000/api/customers',
    PRODUCTS: 'http://localhost:8000/api/products',
    INVOICES: 'http://localhost:8000/api/invoices',
};